// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: redstoneconsolidator/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetPriceFeedRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryGetPriceFeedRequest) Reset()         { *m = QueryGetPriceFeedRequest{} }
func (m *QueryGetPriceFeedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPriceFeedRequest) ProtoMessage()    {}
func (*QueryGetPriceFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{2}
}
func (m *QueryGetPriceFeedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPriceFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPriceFeedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPriceFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPriceFeedRequest.Merge(m, src)
}
func (m *QueryGetPriceFeedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPriceFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPriceFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPriceFeedRequest proto.InternalMessageInfo

func (m *QueryGetPriceFeedRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetPriceFeedResponse struct {
	PriceFeed PriceFeed `protobuf:"bytes,1,opt,name=priceFeed,proto3" json:"priceFeed"`
}

func (m *QueryGetPriceFeedResponse) Reset()         { *m = QueryGetPriceFeedResponse{} }
func (m *QueryGetPriceFeedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPriceFeedResponse) ProtoMessage()    {}
func (*QueryGetPriceFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{3}
}
func (m *QueryGetPriceFeedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPriceFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPriceFeedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPriceFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPriceFeedResponse.Merge(m, src)
}
func (m *QueryGetPriceFeedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPriceFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPriceFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPriceFeedResponse proto.InternalMessageInfo

func (m *QueryGetPriceFeedResponse) GetPriceFeed() PriceFeed {
	if m != nil {
		return m.PriceFeed
	}
	return PriceFeed{}
}

type QueryAllPriceFeedRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPriceFeedRequest) Reset()         { *m = QueryAllPriceFeedRequest{} }
func (m *QueryAllPriceFeedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPriceFeedRequest) ProtoMessage()    {}
func (*QueryAllPriceFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{4}
}
func (m *QueryAllPriceFeedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPriceFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPriceFeedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPriceFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPriceFeedRequest.Merge(m, src)
}
func (m *QueryAllPriceFeedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPriceFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPriceFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPriceFeedRequest proto.InternalMessageInfo

func (m *QueryAllPriceFeedRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPriceFeedResponse struct {
	PriceFeed  []PriceFeed         `protobuf:"bytes,1,rep,name=priceFeed,proto3" json:"priceFeed"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPriceFeedResponse) Reset()         { *m = QueryAllPriceFeedResponse{} }
func (m *QueryAllPriceFeedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPriceFeedResponse) ProtoMessage()    {}
func (*QueryAllPriceFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5369b5728d89bfa, []int{5}
}
func (m *QueryAllPriceFeedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPriceFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPriceFeedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPriceFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPriceFeedResponse.Merge(m, src)
}
func (m *QueryAllPriceFeedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPriceFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPriceFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPriceFeedResponse proto.InternalMessageInfo

func (m *QueryAllPriceFeedResponse) GetPriceFeed() []PriceFeed {
	if m != nil {
		return m.PriceFeed
	}
	return nil
}

func (m *QueryAllPriceFeedResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryParamsResponse")
	proto.RegisterType((*QueryGetPriceFeedRequest)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryGetPriceFeedRequest")
	proto.RegisterType((*QueryGetPriceFeedResponse)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryGetPriceFeedResponse")
	proto.RegisterType((*QueryAllPriceFeedRequest)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryAllPriceFeedRequest")
	proto.RegisterType((*QueryAllPriceFeedResponse)(nil), "kodek16.redstoneconsolidator.redstoneconsolidator.QueryAllPriceFeedResponse")
}

func init() { proto.RegisterFile("redstoneconsolidator/query.proto", fileDescriptor_d5369b5728d89bfa) }

var fileDescriptor_d5369b5728d89bfa = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0xb5, 0x0d, 0x64, 0xf4, 0x34, 0xf6, 0x50, 0x83, 0xac, 0x75, 0xc1, 0x3f, 0x08,
	0xce, 0x90, 0x0a, 0x42, 0x51, 0x91, 0x14, 0x93, 0x1e, 0xec, 0x21, 0xe6, 0x22, 0x78, 0xa9, 0xb3,
	0xd9, 0xd7, 0x75, 0xe9, 0x66, 0x66, 0xbb, 0x33, 0x11, 0x8b, 0xf4, 0xe2, 0x27, 0x10, 0xfc, 0x4e,
	0xd2, 0x93, 0x14, 0xbc, 0x88, 0x07, 0x91, 0xc4, 0x0f, 0xe0, 0xc1, 0x0f, 0x20, 0x3b, 0x33, 0x49,
	0x1b, 0x32, 0x28, 0x6e, 0x7b, 0x5b, 0x66, 0xdf, 0xf7, 0x79, 0x9e, 0xdf, 0xbe, 0xfb, 0x0e, 0x5e,
	0x2f, 0x20, 0x56, 0x5a, 0x0a, 0x18, 0x48, 0xa1, 0x64, 0x96, 0xc6, 0x5c, 0xcb, 0x82, 0xed, 0x8f,
	0xa0, 0x38, 0xa0, 0x79, 0x21, 0xb5, 0x24, 0xad, 0x3d, 0x19, 0xc3, 0x5e, 0xeb, 0x3e, 0xf5, 0x55,
	0x7a, 0x0f, 0x9b, 0xab, 0x89, 0x4c, 0xa4, 0xe9, 0x66, 0xe5, 0x93, 0x15, 0x6a, 0x5e, 0x4d, 0xa4,
	0x4c, 0x32, 0x60, 0x3c, 0x4f, 0x19, 0x17, 0x42, 0x6a, 0xae, 0x53, 0x29, 0x94, 0x7b, 0x7b, 0x67,
	0x20, 0xd5, 0x50, 0x2a, 0x16, 0x71, 0x05, 0xd6, 0x9f, 0xbd, 0x69, 0x45, 0xa0, 0x79, 0x8b, 0xe5,
	0x3c, 0x49, 0x85, 0x29, 0x76, 0xb5, 0xd7, 0xbd, 0xa1, 0x73, 0x5e, 0xf0, 0xe1, 0x54, 0xee, 0x86,
	0xbf, 0xa4, 0x48, 0x07, 0xb0, 0xfb, 0x0a, 0x20, 0xb6, 0x65, 0xe1, 0x2a, 0x26, 0xcf, 0x4a, 0xaf,
	0x9e, 0xe9, 0xed, 0xc3, 0xfe, 0x08, 0x94, 0x0e, 0x05, 0xbe, 0x3c, 0x77, 0xaa, 0x72, 0x29, 0x14,
	0x90, 0xe7, 0xb8, 0x6e, 0x3d, 0xd6, 0xd0, 0x3a, 0xba, 0x7d, 0x71, 0x63, 0x93, 0xfe, 0xf7, 0xa7,
	0xa1, 0x56, 0x72, 0x6b, 0xf9, 0xe8, 0xfb, 0xb5, 0x5a, 0xdf, 0xc9, 0x85, 0x14, 0xaf, 0x19, 0xbf,
	0x6d, 0xd0, 0xbd, 0x32, 0x61, 0x17, 0x20, 0x76, 0x59, 0x08, 0xc1, 0xcb, 0x82, 0x0f, 0xc1, 0x58,
	0x36, 0xfa, 0xe6, 0x39, 0x3c, 0xc4, 0x57, 0x3c, 0xf5, 0x2e, 0xe5, 0x4b, 0xdc, 0xc8, 0xa7, 0x87,
	0x2e, 0xe8, 0xc3, 0x2a, 0x41, 0xa7, 0x1a, 0x2e, 0xeb, 0x89, 0x68, 0x18, 0xb9, 0xb8, 0xed, 0x2c,
	0x5b, 0x88, 0xdb, 0xc5, 0xf8, 0x64, 0x5c, 0xce, 0xfe, 0x26, 0xb5, 0xb3, 0xa5, 0xe5, 0x6c, 0xa9,
	0xfd, 0xb7, 0xdc, 0x6c, 0x69, 0x8f, 0x27, 0xe0, 0x7a, 0xfb, 0xa7, 0x3a, 0xc3, 0x4f, 0xc8, 0x31,
	0xce, 0x9b, 0xf8, 0x19, 0x2f, 0x9c, 0x3b, 0x23, 0xd9, 0x9e, 0xe3, 0x58, 0x32, 0x1c, 0xb7, 0xfe,
	0xc9, 0x61, 0xe3, 0x9d, 0x06, 0xd9, 0xf8, 0xbc, 0x82, 0x57, 0x0c, 0x08, 0xf9, 0x86, 0x70, 0xdd,
	0x8e, 0x9f, 0x74, 0x2a, 0x84, 0x5d, 0xfc, 0x4f, 0x9b, 0xdd, 0xb3, 0xca, 0xd8, 0xbc, 0x61, 0xfb,
	0xfd, 0x97, 0x9f, 0x1f, 0x97, 0x1e, 0x90, 0x4d, 0xe6, 0xf4, 0x98, 0x77, 0x7b, 0xfe, 0xb2, 0x75,
	0xe4, 0x37, 0xc2, 0x8d, 0xd9, 0xe7, 0x24, 0x4f, 0xab, 0x06, 0xf3, 0x6c, 0x40, 0x73, 0xe7, 0x7c,
	0xc4, 0x1c, 0xeb, 0x8e, 0x61, 0xed, 0x92, 0x27, 0x55, 0x58, 0x67, 0xd7, 0x07, 0x7b, 0x57, 0x2e,
	0xe2, 0x21, 0xf9, 0x85, 0xf0, 0xa5, 0x99, 0x47, 0x3b, 0xcb, 0xaa, 0x93, 0x7b, 0x96, 0xa9, 0x3a,
	0xb9, 0x6f, 0x69, 0xc2, 0x8e, 0x21, 0x7f, 0x4c, 0x1e, 0x9d, 0x89, 0x7c, 0x6b, 0xf7, 0x68, 0x1c,
	0xa0, 0xe3, 0x71, 0x80, 0x7e, 0x8c, 0x03, 0xf4, 0x61, 0x12, 0xd4, 0x8e, 0x27, 0x41, 0xed, 0xeb,
	0x24, 0xa8, 0xbd, 0xe8, 0x24, 0xa9, 0x7e, 0x3d, 0x8a, 0xe8, 0x40, 0x0e, 0x17, 0x2c, 0xee, 0xce,
	0xc9, 0xbd, 0xf5, 0xbb, 0xe8, 0x83, 0x1c, 0x54, 0x54, 0x37, 0x57, 0xf3, 0xbd, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0xc0, 0xfa, 0xef, 0x9b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a PriceFeed by index.
	PriceFeed(ctx context.Context, in *QueryGetPriceFeedRequest, opts ...grpc.CallOption) (*QueryGetPriceFeedResponse, error)
	// Queries a list of PriceFeed items.
	PriceFeedAll(ctx context.Context, in *QueryAllPriceFeedRequest, opts ...grpc.CallOption) (*QueryAllPriceFeedResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PriceFeed(ctx context.Context, in *QueryGetPriceFeedRequest, opts ...grpc.CallOption) (*QueryGetPriceFeedResponse, error) {
	out := new(QueryGetPriceFeedResponse)
	err := c.cc.Invoke(ctx, "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/PriceFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PriceFeedAll(ctx context.Context, in *QueryAllPriceFeedRequest, opts ...grpc.CallOption) (*QueryAllPriceFeedResponse, error) {
	out := new(QueryAllPriceFeedResponse)
	err := c.cc.Invoke(ctx, "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/PriceFeedAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a PriceFeed by index.
	PriceFeed(context.Context, *QueryGetPriceFeedRequest) (*QueryGetPriceFeedResponse, error)
	// Queries a list of PriceFeed items.
	PriceFeedAll(context.Context, *QueryAllPriceFeedRequest) (*QueryAllPriceFeedResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PriceFeed(ctx context.Context, req *QueryGetPriceFeedRequest) (*QueryGetPriceFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PriceFeed not implemented")
}
func (*UnimplementedQueryServer) PriceFeedAll(ctx context.Context, req *QueryAllPriceFeedRequest) (*QueryAllPriceFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PriceFeedAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PriceFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPriceFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PriceFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/PriceFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PriceFeed(ctx, req.(*QueryGetPriceFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PriceFeedAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPriceFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PriceFeedAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kodek16.redstoneconsolidator.redstoneconsolidator.Query/PriceFeedAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PriceFeedAll(ctx, req.(*QueryAllPriceFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kodek16.redstoneconsolidator.redstoneconsolidator.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PriceFeed",
			Handler:    _Query_PriceFeed_Handler,
		},
		{
			MethodName: "PriceFeedAll",
			Handler:    _Query_PriceFeedAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redstoneconsolidator/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPriceFeedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPriceFeedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPriceFeedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPriceFeedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPriceFeedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPriceFeedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PriceFeed.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPriceFeedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPriceFeedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPriceFeedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPriceFeedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPriceFeedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPriceFeedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PriceFeed) > 0 {
		for iNdEx := len(m.PriceFeed) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceFeed[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPriceFeedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPriceFeedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriceFeed.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPriceFeedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPriceFeedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PriceFeed) > 0 {
		for _, e := range m.PriceFeed {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPriceFeedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPriceFeedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPriceFeedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPriceFeedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPriceFeedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPriceFeedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceFeed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriceFeed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPriceFeedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPriceFeedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPriceFeedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPriceFeedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPriceFeedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPriceFeedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceFeed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceFeed = append(m.PriceFeed, PriceFeed{})
			if err := m.PriceFeed[len(m.PriceFeed)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
